name: Run tests

on: 
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    
    - name: Install xcpretty
      run: gem install xcpretty
    
    - name: Update submodules
      run: git submodule sync --recursive && git submodule update --recursive --init
      
    - name: Setup simulator
      id: version
      run: |
        CURRENT_SIMULATOR_UUID=$(xcrun simctl create TestDevice com.apple.CoreSimulator.SimDeviceType.iPhone-11 com.apple.CoreSimulator.SimRuntime.iOS-13-3)
        echo "::set-env name=CURRENT_SIMULATOR_UUID::$CURRENT_SIMULATOR_UUID"
        
    
    - name: Test generated schema
      run: |
        ./Scripts/test_buy
        ./Scripts/test_buy_tv
        ./Scripts/test_buy_watch
        ./Scripts/test_pay
